import os
import sqlite3
from contextlib import closing

from runtime import artifacts_dir, on_vercel

POSTGRES = bool(os.environ.get('DATABASE_URL'))

_ID = (
    'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    if POSTGRES else
    'id INTEGER PRIMARY KEY AUTOINCREMENT'
)

USERS = f"""
CREATE TABLE IF NOT EXISTS users (
    {_ID},
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email TEXT UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    terms_accepted_at TIMESTAMP,
    signup_ip TEXT,
    signup_user_agent TEXT,
    signup_accept_language TEXT,
    signup_country TEXT,
    signup_region TEXT,
    signup_city TEXT,
    last_login_at TIMESTAMP,
    last_login_ip TEXT,
    last_login_user_agent TEXT,
    last_login_country TEXT
)
"""

POSTS = f"""
CREATE TABLE IF NOT EXISTS posts (
    {_ID},
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    preview_text TEXT NOT NULL,
    preview_image_url TEXT,
    body_md TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""

POSTS_INDEX = """
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC)
"""

STORED = """
CREATE TABLE IF NOT EXISTS stored_images (
    url TEXT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
"""

SCHEMA = (USERS, POSTS, POSTS_INDEX, STORED)


def _sqlite_path():
    if on_vercel():
        raise RuntimeError('Refusing to open SQLite on Vercel. Set DATABASE_URL.')
    return os.path.join(artifacts_dir(), 'database.db')


def _sql(sql):
    if POSTGRES:
        return sql.replace('?', '%s')
    return sql


def _row(row):
    if row is None:
        return None
    if isinstance(row, dict):
        return row
    return dict(row)


def get_db_connection():
    if POSTGRES:
        import psycopg
        from psycopg.rows import dict_row
        conn = psycopg.connect(os.environ['DATABASE_URL'], row_factory=dict_row)
        return conn

    conn = sqlite3.connect(_sqlite_path(), timeout=15.0)
    conn.execute('PRAGMA journal_mode=WAL;')
    conn.execute('PRAGMA foreign_keys=ON;')
    conn.row_factory = sqlite3.Row
    return conn


def init_schema():
    with closing(get_db_connection()) as conn:
        with conn:
            for stmt in SCHEMA:
                conn.execute(stmt.strip())


def fetch_one(sql, params=()):
    with closing(get_db_connection()) as conn:
        cur = conn.execute(_sql(sql), params)
        return _row(cur.fetchone())


def fetch_all(sql, params=()):
    with closing(get_db_connection()) as conn:
        cur = conn.execute(_sql(sql), params)
        return [_row(r) for r in cur.fetchall()]


def execute(sql, params=()):
    with closing(get_db_connection()) as conn:
        with conn:
            cur = conn.execute(_sql(sql), params)
            return cur.lastrowid if not POSTGRES else None


def insert_returning_id(sql, params=()):
    with closing(get_db_connection()) as conn:
        with conn:
            if POSTGRES:
                cur = conn.execute(_sql(sql) + ' RETURNING id', params)
                row = cur.fetchone()
                return row['id']
            cur = conn.execute(sql, params)
            return cur.lastrowid


def get_session_user(user_id):
    return fetch_one('SELECT id, username FROM users WHERE id = ?', (user_id,))


def get_user_by_username(username):
    return fetch_one('SELECT * FROM users WHERE username = ?', (username,))


def get_user_by_email(email):
    if not email:
        return None
    return fetch_one('SELECT * FROM users WHERE email = ?', (email,))


def create_user(username, password_hash, email, meta):
    return insert_returning_id(
        """
        INSERT INTO users (
            username, password_hash, email, terms_accepted_at,
            signup_ip, signup_user_agent, signup_accept_language,
            signup_country, signup_region, signup_city,
            last_login_at, last_login_ip, last_login_user_agent, last_login_country
        ) VALUES (?, ?, ?, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?, ?, ?)
        """,
        (
            username,
            password_hash,
            email,
            meta.get('ip'),
            meta.get('user_agent'),
            meta.get('accept_language'),
            meta.get('country'),
            meta.get('region'),
            meta.get('city'),
            meta.get('ip'),
            meta.get('user_agent'),
            meta.get('country'),
        ),
    )


def update_login_meta(user_id, meta):
    execute(
        """
        UPDATE users SET
            last_login_at = CURRENT_TIMESTAMP,
            last_login_ip = ?,
            last_login_user_agent = ?,
            last_login_country = ?
        WHERE id = ?
        """,
        (meta.get('ip'), meta.get('user_agent'), meta.get('country'), user_id),
    )


def slug_exists(slug):
    return fetch_one('SELECT id FROM posts WHERE slug = ?', (slug,)) is not None


def count_posts():
    row = fetch_one('SELECT COUNT(*) AS n FROM posts')
    return int(row['n']) if row else 0


def create_post(slug, title, preview_text, preview_image_url, body_md, author_id):
    return insert_returning_id(
        """
        INSERT INTO posts (slug, title, preview_text, preview_image_url, body_md, author_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (slug, title, preview_text, preview_image_url, body_md, author_id),
    )


def update_post(post_id, title, preview_text, preview_image_url, body_md):
    execute(
        """
        UPDATE posts SET
            title = ?, preview_text = ?, preview_image_url = ?,
            body_md = ?, updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        (title, preview_text, preview_image_url, body_md, post_id),
    )


def delete_post(post_id):
    execute('DELETE FROM posts WHERE id = ?', (post_id,))


def get_post_by_slug(slug):
    return fetch_one(
        """
        SELECT posts.*, users.username AS author_username
        FROM posts JOIN users ON users.id = posts.author_id
        WHERE posts.slug = ?
        """,
        (slug,),
    )


def list_post_media():
    return fetch_all('SELECT id, preview_image_url, body_md FROM posts')


def list_stored_images():
    return fetch_all('SELECT url FROM stored_images')


def record_stored_image(url):
    if not url:
        return
    if POSTGRES:
        sql = 'INSERT INTO stored_images (url) VALUES (?) ON CONFLICT (url) DO NOTHING'
    else:
        sql = 'INSERT OR IGNORE INTO stored_images (url) VALUES (?)'
    execute(sql, (url,))


def delete_stored_image(url):
    execute('DELETE FROM stored_images WHERE url = ?', (url,))


def list_posts():
    return fetch_all(
        """
        SELECT posts.*, users.username AS author_username
        FROM posts JOIN users ON users.id = posts.author_id
        ORDER BY posts.created_at DESC
        """
    )
